version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
jobs:
  build:
    docker:
      - image: 'cimg/base:2020.01'
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive --depth=1
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install --no-install-recommends -y devscripts equivs debhelper libdistro-info-perl
            sudo mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control
      - run:
          name: Build DSCs
          command: |
            export DEB_DISTRO=$(lsb_release -cs)
            tools/makedeb --dsc
            no_output_timeout: 30m
      - run:
          name: Move DSCs
          command: mkdir source && mv ../*~testing.* source
      - run:
          name: Build DEBs
          command: |
            export DEB_DISTRO=$(lsb_release -cs)
            tools/makedeb
      - run:
          name: Move DEBs
          command: mkdir dist && mv ../*.deb dist
      - store_artifacts:
          path: dist/
          destination: debs
      - store_artifacts:
          path: source/
          destination: source
