version: 2.1
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
jobs:
  build:
    machine:
      image: 'ubuntu-1604:202004-01'
    steps:
      - git-shallow-clone/checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init --recursive --depth=1
      - run:
          name: Install dependencies
          command: |
            wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
            sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
            sudo apt-get update && sudo apt-get install --no-install-recommends -y devscripts equivs debhelper libdistro-info-perl
            sudo mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control
      - run:
          name: Build DSCs
          no_output_timeout: 30m
          command: |
            export DEB_DISTRO=$(lsb_release -cs)
            tools/makedeb --dsc
      - run:
          name: Move DSCs
          command: mkdir source && mv ../*~$(lsb_release -cs).* source
      - run:
          name: Build DEBs
          no_output_timeout: 30m
          command: |
            export DEB_DISTRO=$(lsb_release -cs)
            tools/makedeb
      - run:
          name: Move DEBs
          command: mkdir dist && mv ../*.deb dist
      - store_artifacts:
          path: dist/
          destination: debs
      - store_artifacts:
          path: source/
          destination: source
