name: Darling CI

on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
      with:
        submodules: recursive
        lfs: true
    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install devscripts equivs debhelper
        sudo mk-build-deps -ir
    - name: Build DEB
      run: tools/makedeb
    - name: Move DEBs
      run: mkdir dist && mv ../*.deb dist
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: 'debs'
        path: dist/

  build-dsc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
      with:
        submodules: recursive
        lfs: true
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install devscripts dpkg-dev debhelper
    - name: Build DSC
      run: tools/makedeb --dsc
    - name: Move DSCs
      run: mkdir source && mv ../*~testing.* source
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: 'source'
        path: source/
